name: Vulnerability Scan

on:
  push:
    branches:
      - master  # Replace with your default branch if it's different
  pull_request:
    branches:
      - master  # Replace with your default branch if it's different

jobs:
  vulncheck:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.2'  # Set to your required Go version

      # Step 3: Install govulncheck
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      # Step 4: Run govulncheck to find vulnerabilities
      - name: Run govulncheck and check vulnerabilities
        run: |
          govulncheck ./... > vuln_report.txt
          if [ -s vuln_report.txt ]; then
            cat vuln_report.txt
          else
            echo "No vulnerabilities found."
          fi

      # Step 5: Upload the vulnerability report as an artifact
      - name: Upload vulnerability report
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-report
          path: vuln_report.txt

      # Step 6: Create a summary for the vulnerability report
      - name: Create vulnerability summary
        run: |
          if [ -s vuln_report.txt ]; then
            echo "## Vulnerabilities Found" >> summary.md
            cat vuln_report.txt >> summary.md
            echo "SUMMARY=$(cat summary.md)" >> $GITHUB_ENV  # Set summary in environment variable
          else
            echo "No vulnerabilities found" >> summary.md
            echo "SUMMARY=No vulnerabilities found" >> $GITHUB_ENV  # Set summary in environment variable
          fi

      # Step 7: Commit and push the report to the repository
      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add summary.md vuln_report.txt
          git commit -m "Add vulnerability report and summary"
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
