name: Vulnerability Scan

on:
  push:
    branches:
      - master  # or use 'main' if that's your default branch
  pull_request:
    branches:
      - master  # or 'main'

jobs:
  vulncheck:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.2'

      # Install govulncheck
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      # Verify govulncheck installation
      - name: Verify govulncheck installation
        run: |
          echo "Verifying govulncheck installation..."
          govulncheck --version  # Verify the installation of govulncheck

      # Run govulncheck and check vulnerabilities
      - name: Run govulncheck and check vulnerabilities
        run: |
          set -e  # Ensure the script fails if any command fails
          echo "Running govulncheck..."
          govulncheck --version  # Verify the installed version of govulncheck
          govulncheck ./... > vuln_report.txt 2>&1 || echo "govulncheck completed with errors, continue..."
          if [ -s vuln_report.txt ]; then
            echo "Vulnerabilities found. Printing report..."
            cat vuln_report.txt
          else
            echo "No vulnerabilities found."
          fi

      # Create a summary.md file for the vulnerability report
      - name: Create summary.md with vulnerabilities
        run: |
          if [ -s vuln_report.txt ]; then
            echo "## Vulnerabilities Found" > summary.md
            cat vuln_report.txt >> summary.md
          else
            echo "## No vulnerabilities found" > summary.md
          fi

      # Commit the summary.md and vuln_report.txt to the repository
      - name: Commit vulnerability report and summary.md to repository
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add summary.md vuln_report.txt
          git commit -m "Add vulnerability report and summary"
          git push origin HEAD:master  # Replace 'master' with 'main' if necessary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
